version: '3'

networks:
  nginx-php74-mysql5:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql5-service
    networks:
      - nginx-php74-mysql5

  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-mysql5


  mysql5-service:
    image: mysql:5.7.22
    container_name: mysql5-container
    ports:
      - "33069:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ubuntu
      MYSQL_PASSWORD: ubuntu
    networks:
      - nginx-php74-mysql5
