auctions:
    path: /auctions
    controller: App\Controller\AuctionController::index

auction_detail:
    path: /auction/{id}
    controller: App\Controller\AuctionController::detail

auction_create:
    path: /create-auction
    controller: App\Controller\AuctionController::create

auction_edit:
    path: /edit-auction/{id}
    controller: App\Controller\AuctionController::edit

register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout